pub const Format = enum(u16) {
    unknown,
    // opengl specific
    l8_a8_unorm,
    l8_unorm,
    a8_unorm,

    d16_unorm_s8_uint,
    d24_unorm_s8_uint,
    d32_sfloat_s8_uint,

    r8_unorm,
    r8_snorm,
    r8_uint,
    r8_sint,
    rg8_unorm,
    rg8_snorm,
    rg8_uint,
    rg8_sint,
    bgra8_unorm,
    bgra8_srgb,
    bgr8_unorm,
    rgb8_unorm,
    rgba8_unorm,
    rgba8_snorm,
    rgba8_uint,
    rgba8_sint,
    rgba8_srgb,
    r16_unorm,
    r16_snorm,
    r16_uint,
    r16_sint,
    r16_sfloat,
    rg16_unorm,
    rg16_snorm,
    rg16_uint,
    rg16_sint,
    rg16_sfloat,
    rgba16_unorm,
    rgba16_snorm,
    rgba16_uint,
    rgba16_sint,
    rgba16_sfloat,
    r32_uint,
    r32_sint,
    r32_sfloat,
    rg32_uint,
    rg32_sint,
    rg32_sfloat,
    rgb32_uint,
    rgb32_sint,
    rgb32_sfloat,
    rgba32_uint,
    rgba32_sint,
    rgba32_sfloat,
    r10_g10_b10_a2_unorm,
    r10_g10_b10_a2_uint,
    r11_g11_b10_ufloat,
    r9_g9_b9_e5_unorm,
    r5_g6_b5_unorm,
    r5_g5_b5_a1_unorm,
    r4_g4_b4_a4_unorm,
    bc1_rgba_unorm,
    bc1_rgba_srgb,
    bc2_rgba_unorm,
    bc2_rgba_srgb,
    bc3_rgba_unorm,
    bc3_rgba_srgb,
    bc4_r_unorm,
    bc4_r_snorm,
    bc5_rg_unorm,
    bc5_rg_snorm,
    bc6h_rgb_ufloat,
    bc6h_rgb_sfloat,
    bc7_rgba_unorm,
    bc7_rgba_srgb,
    d16_unorm,
    d32_sfloat,
    d32_sfloat_s8_uint_x24,
    r24_unorm_x8,
    x24_r8_uint,
    x32_r8_uint_x24,
    r32_sfloat_x8_x24,

    etc1_r8g8b8_oes, // r_format_etc2_r8g8b8_unorm is a superset

    etc2_r8g8b8_unorm,
    etc2_r8g8b8_srgb,
    etc2_r8g8b8a1_unorm,
    etc2_r8g8b8a1_srgb,
    etc2_r8g8b8a8_unorm,
    etc2_r8g8b8a8_srgb,
    etc2_eac_r11_unorm,
    etc2_eac_r11_snorm,
    etc2_eac_r11g11_unorm,
    etc2_eac_r11g11_snorm,
};

pub const FormatProps = struct {
    name: []const u8, // format name
    format: Format, // self
    red_or_depth_bits: u8 = 0,
    green_or_stencil_bits: u8 = 0,
    blue_bits: u8 = 0, // B bits (0 if channels < 3)
    alpha_bits: u8 = 0, // A (or shared exponent) bits (0 if channels < 4)
    luminance_bits: u8, // L luminance
    stride: u6 = 0, // block size in bytes
    block_width: u4 = 0, // 1 for plain formats, >1 for compressed
    block_height: u4 = 0, // 1 for plain formats, >1 for compressed
    is_bgr: bool = 0, // reversed channels (RGBA => BGRA)
    is_compressed: bool = 0, // block-compressed format
    is_depth: bool = 0, // has depth component
    is_exp_shared: bool = 0, // shared exponent in alpha channel
    is_float: bool = 0, // floating point
    is_packed: bool = 0, // 16- or 32- bit packed
    is_integer: bool = 0, // integer
    is_norm: bool = 0, // [0; 1] normalized
    is_signed: bool = 0, // signed
    is_srgb: bool = 0, // sRGB
    is_stencil: bool = 0, // has stencil component
};


pub fn get_props(format: Format) FormatProps {
    switch (format) {
        .l8_a8_unorm => .{
            .name = "l8_a8_unorm",
            .format = .l8_a8_unorm,
            .alpha_bits = 8,
            .luminance_bits = 8,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .l8_unorm => .{
            .name = "l8_unorm",
            .luminance_bits = 8,
            .stride = 1,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .a8_unorm => .{
            .name = "rgba8_snormunorm",
            .alpha_bits = 8,
            .stride = 1,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .d16_unorm_s8_uint => .{
            .name = "d16_unorm_s8_uint",
            .red_or_depth_bits = 16,
            .green_or_stencil_bits = 8,
            .stride = 3,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_depth = 1,
            .is_stencil = 1,
        },
        .d24_unorm_s8_uint => .{
            .name = "d24_unorm_s8_uint",
            .red_or_depth_bits = 24,
            .green_or_stencil_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_depth = 1,
            .is_stencil = 1,
        },
        .d32_sfloat_s8_uint => .{ .name = "d32_sfloat_s8_uint", .red_or_depth_bits = 24, .green_or_stencil_bits = 8, .stride = 8, .block_width = 1, .block_height = 1, .is_depth = 1, .is_stencil = 1, .is_float = 1 },
        .r8_unorm => .{
            .name = "r8_unorm",
            .red_or_depth_bits = 8,
            .stride = 1,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r8_snorm => .{ .name = "r8_snorm", .red_or_depth_bits = 8, .stride = 1, .block_width = 1, .block_height = 1, .is_norm = 1, .is_signed = 1 },
        .r8_uint => .{
            .name = "r8_uint",
            .red_or_depth_bits = 8,
            .stride = 1,
            .block_width = 1,
            .block_height = 1,
        },
        .r8_sint => .{
            .name = "r8_sint",
            .red_or_depth_bits = 8,
            .stride = 1,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rg8_unorm => .{
            .name = "rg8_unorm",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .rg8_snorm => .{
            .name = "rg8_snorm",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .rg8_uint => .{
            .name = "rg8_uint",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
        },
        .rg8_sint => .{
            .name = "rg8_sint",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .bgra8_unorm => .{
            .name = "bgra8_unorm",
            .blue_bits = 8,
            .greenbits = 8,
            .red_or_depth_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_bgr = 1,
        },
        .bgra8_srgb => .{
            .name = "bgra8_srgb",
            .blue_bits = 8,
            .greenbits = 8,
            .red_or_depth_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_srgb = 1,
            .is_bgr = 1,
        },
        .bgr8_unorm => .{
            .name = "bgr8_unorm",
            .blue_bits = 8,
            .greenbits = 8,
            .red_or_depth_bits = 8,
            .stride = 3,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_bgr = 1,
        },
        .rgb8_unorm => .{
            .name = "rgb8_unorm",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .stride = 3,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .rgba8_unorm => .{
            .name = "rgba8_unorm",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .rgba8_snorm => .{
            .name = "rgba8_snorm",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .rgba8_uint => .{
            .name = "rgba8_uint",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rgba8_sint => .{
            .name = "rgba8_sint",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
            .is_signed = 1,
        },
        .rgba8_srgb => .{
            .name = "rgba8_srgb",
            .red_or_depth_bits = 8,
            .greenbits = 8,
            .blue_bits = 8,
            .alpha_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_srgb = 1,
        },
        .r16_unorm => .{
            .name = "r16_unorm",
            .red_or_depth_bits = 16,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r16_snorm => .{
            .name = "r16_snorm",
            .red_or_depth_bits = 16,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .r16_uint => .{
            .name = "r16_uint",
            .red_or_depth_bits = 16,
            .block_width = 1,
            .block_height = 1,
            .stride = 2,
        },
        .r16_sint => .{
            .name = "r16_sint",
            .red_or_depth_bits = 16,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .r16_sfloat => .{
            .name = "r16_sfloat",
            .red_or_depth_bits = 16,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .rg16_unorm => .{
            .name = "rg16_unorm",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .rg16_snorm => .{
            .name = "rg16_snorm",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .rg16_uint => .{
            .name = "rg16_uint",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
        },
        .rg16_sint => .{
            .name = "rg16_sint",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rg16_sfloat => .{
            .name = "rg16_sfloat",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .rgba16_unorm => .{
            .name = "rgba16_unorm",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .alpha_bits = 16,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .rgba16_snorm => .{
            .name = "rgba16_snorm",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .alpha_bits = 16,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .rgba16_uint => .{
            .name = "rgba16_uint",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .alpha_bits = 16,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
        },
        .rgba16_sint => .{
            .name = "rgba16_sint",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .alpha_bits = 16,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rgba16_sfloat => .{
            .name = "rgba16_sfloat",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .alpha_bits = 16,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .r32_uint => .{
            .name = "r32_uint",
            .red_or_depth_bits = 32,
            .block_width = 1,
            .block_height = 1,
            .stride = 4,
        },
        .r32_sint => .{
            .name = "r32_sint",
            .red_or_depth_bits = 32,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .r32_sfloat => .{
            .name = "r32_sfloat",
            .red_or_depth_bits = 32,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .rg32_uint => .{
            .name = "rg32_uint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .block_width = 1,
            .block_height = 1,
            .stride = 8,
        },
        .rg32_sint => .{
            .name = "rg32_sint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rg32_sfloat => .{
            .name = "rg32_sfloat",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .rgb32_uint => .{
            .name = "rgb32_uint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .stride = 12,
            .block_width = 1,
            .block_height = 1,
        },
        .rgb32_sint => .{
            .name = "rgb32_sint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .stride = 12,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rgb32_sfloat => .{
            .name = "rgb32_sfloat",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .stride = 12,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .rgba32_uint => .{
            .name = "rgba32_uint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .alpha_bits = 32,
            .stride = 16,
            .block_width = 1,
            .block_height = 1,
        },
        .rgba32_sint => .{
            .name = "rgba32_sint",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .alpha_bits = 32,
            .stride = 16,
            .block_width = 1,
            .block_height = 1,
            .is_integer = 1,
        },
        .rgba32_sfloat => .{
            .name = "rgba32_sfloat",
            .red_or_depth_bits = 32,
            .greenbits = 32,
            .blue_bits = 32,
            .alpha_bits = 32,
            .stride = 16,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .r10_g10_b10_a2_unorm => .{
            .name = "r10_g10_b10_a2_unorm",
            .red_or_depth_bits = 10,
            .greenbits = 10,
            .blue_bits = 10,
            .alpha_bits = 2,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r10_g10_b10_a2_uint => .{
            .name = "r10_g10_b10_a2_uint",
            .red_or_depth_bits = 10,
            .greenbits = 10,
            .blue_bits = 10,
            .alpha_bits = 2,
            .stride = 4,
        },
        .r11_g11_b10_ufloat => .{
            .name = "r11_g11_b10_ufloat",
            .red_or_depth_bits = 11,
            .greenbits = 11,
            .blue_bits = 10,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .r9_g9_b9_e5_unorm => .{
            .name = "r9_g9_b9_e5_unorm",
            .red_or_depth_bits = 9,
            .greenbits = 9,
            .blue_bits = 9,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r5_g6_b5_unorm => .{
            .name = "r5_g6_b5_unorm",
            .red_or_depth_bits = 5,
            .greenbits = 6,
            .blue_bits = 5,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r5_g5_b5_a1_unorm => .{
            .name = "r5_g5_b5_a1_unorm",
            .red_or_depth_bits = 5,
            .greenbits = 5,
            .blue_bits = 5,
            .alpha_bits = 1,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .r4_g4_b4_a4_unorm => .{
            .name = "r4_g4_b4_a4_unorm",
            .red_or_depth_bits = 4,
            .greenbits = 4,
            .blue_bits = 4,
            .alpha_bits = 4,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .bc1_rgba_unorm => .{
            .name = "bc1_rgba_unorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc1_rgba_srgb => .{
            .name = "bc1_rgba_srgb",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .bc2_rgba_unorm => .{
            .name = "bc2_rgba_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc2_rgba_srgb => .{
            .name = "bc2_rgba_srgb",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .bc3_rgba_unorm => .{
            .name = "bc3_rgba_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc3_rgba_srgb => .{
            .name = "bc3_rgba_srgb",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .bc4_r_unorm => .{
            .name = "bc4_r_unorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc4_r_snorm => .{
            .name = "bc4_r_snorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .bc5_rg_unorm => .{
            .name = "bc5_rg_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc5_rg_snorm => .{
            .name = "bc5_rg_snorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .bc6h_rgb_ufloat => .{
            .name = "bc6h_rgb_ufloat",
            .red_or_depth_bits = 16,
            .greenbits = 16,
            .blue_bits = 16,
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_float = 1,
        },
        .bc6h_rgb_sfloat => .{
            .name = "bc6h_rgb_sfloat",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_float = 1,
        },
        .bc7_rgba_unorm => .{
            .name = "bc7_rgba_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .bc7_rgba_srgb => .{
            .name = "bc7_rgba_srgb",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .d16_unorm => .{
            .name = "d16_unorm",
            .red_or_depth_bits = 16,
            .stride = 2,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
            .is_depth = 1,
        },
        .d32_sfloat => .{
            .name = "d32_sfloat",
            .red_or_depth_bits = 32,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_depth = 1,
            .is_float = 1,
        },
        .d32_sfloat_s8_uint_x24 => .{
            .name = "d32_sfloat_s8_uint_x24",
            .red_or_depth_bits = 32,
            .green_or_stencil_bits = 8,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_depth = 1,
            .is_stencil = 1,
            .is_float = 1,
        },
        .r24_unorm_x8 => .{
            .name = "r24_unorm_x8",
            .red_or_depth_bits = 24,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
            .is_norm = 1,
        },
        .x24_r8_uint => .{
            .name = "x24_r8_uint",
            .red_or_depth_bits = 8,
            .stride = 4,
            .block_width = 1,
            .block_height = 1,
        },
        .x32_r8_uint_x24 => .{
            .name = "x32_r8_uint_x24",
            .red_or_depth_bits = 8,
            .stride = 8,
        },
        .r32_sfloat_x8_x24 => .{
            .name = "r32_sfloat_x8_x24",
            .red_or_depth_bits = 32,
            .stride = 8,
            .block_width = 1,
            .block_height = 1,
            .is_float = 1,
        },
        .etc1_r8g8b8_oes => .{
            .name = "etc1_r8g8b8_oes",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
        },
        .etc2_r8g8b8_unorm => .{
            .name = "etc2_r8g8b8_unorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .etc2_r8g8b8_srgb => .{
            .name = "etc2_r8g8b8_srgb",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .etc2_r8g8b8a1_unorm => .{
            .name = "etc2_r8g8b8a1_unorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .etc2_r8g8b8a1_srgb => .{
            .name = "etc2_r8g8b8a1_srgb",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .etc2_r8g8b8a8_unorm => .{
            .name = "etc2_r8g8b8a8_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .etc2_r8g8b8a8_srgb => .{
            .name = "etc2_r8g8b8a8_srgb",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_srgb = 1,
        },
        .etc2_eac_r11_unorm => .{
            .name = "etc2_eac_r11_unorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .etc2_eac_r11_snorm => .{
            .name = "etc2_eac_r11_snorm",
            .stride = 8,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        .etc2_eac_r11g11_unorm => .{
            .name = "etc2_eac_r11g11_unorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
        },
        .etc2_eac_r11g11_snorm => .{
            .name = "etc2_eac_r11g11_snorm",
            .stride = 16,
            .block_width = 4,
            .block_height = 4,
            .is_compressed = 1,
            .is_norm = 1,
            .is_signed = 1,
        },
        else => FormatProps{ .name = "unknown", .format = .unknown },
    }
}
